/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.hms.novelreadingapp.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;

//import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
//import com.huawei.agconnect.cloud.database.annotations.Indexes;
//import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType Novel.
 *
 * @since 2021-12-18
 */
//@PrimaryKeys({"id"})
//@Indexes({"id:id"})
public final class Novel extends CloudDBZoneObject {
    private String id;

    private String name;

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    private String author;

    private String chapter_quantity;

    private String description;

    private String image;

    public Novel(String id, String name, String author, String chapter_quantity, String description, String image) {
        this.id = id;
        this.name = name;
        this.author = author;
        this.chapter_quantity = chapter_quantity;
        this.description = description;
        this.image = image;
    }
    public Novel( String name, String author, String chapter_quantity, String description, String image) {
        this.name = name;
        this.author = author;
        this.chapter_quantity = chapter_quantity;
        this.description = description;
        this.image = image;
    }
    public Novel(){

    }
    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setChapter_quantity(String chapter_quantity) {
        this.chapter_quantity = chapter_quantity;
    }

    public String getChapter_quantity() {
        return chapter_quantity;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getImage() {
        return image;
    }

}
