/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.hms.novelreadingapp.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;

//import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
//import com.huawei.agconnect.cloud.database.annotations.Indexes;
//import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType Novel.
 *
 * @since 2021-12-18
 */
//@PrimaryKeys({"novel_id"})
//@Indexes({"id:novel_id"})
public final class Novel extends CloudDBZoneObject {
    private String novel_id;

    private String novel_name;

    private String novel_chapter_quantity;

    private String novel_description;

    private String novel_image;

//    public Novel() {
//        super(this);
//    }

    public void setNovel_id(String novel_id) {
        this.novel_id = novel_id;
    }

    public String getNovel_id() {
        return novel_id;
    }

    public void setNovel_name(String novel_name) {
        this.novel_name = novel_name;
    }

    public String getNovel_name() {
        return novel_name;
    }

    public void setNovel_chapter_quantity(String novel_chapter_quantity) {
        this.novel_chapter_quantity = novel_chapter_quantity;
    }

    public String getNovel_chapter_quantity() {
        return novel_chapter_quantity;
    }

    public void setNovel_description(String novel_description) {
        this.novel_description = novel_description;
    }

    public String getNovel_description() {
        return novel_description;
    }

    public void setNovel_image(String novel_image) {
        this.novel_image = novel_image;
    }

    public String getNovel_image() {
        return novel_image;
    }

}
